name: build-docker

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'



jobs:

  buildx:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Prepare
        id: prepare
        run: |
          echo ::set-output name=build_repo::wallabag/docker
          echo ::set-output name=docker_image::ghcr.io/ejsmit/wallabag
          echo ::set-output name=github_username::ejsmit
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.prepare.outputs.build_repo }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.prepare.outputs.github_username }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.prepare.outputs.docker_image }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        